# Generated by Django 5.2.4 on 2025-07-09 13:29

from django.db import migrations

def create_default_categories(apps, schema_editor):
    Category = apps.get_model('category', 'Category')
    default_categories = [
        # Expense
        {'name': 'Housing', 'description': 'Rent, mortgage, etc.', 'type': 'expense'},
        {'name': 'Food', 'description': 'General food expenses.', 'type': 'expense'},
        {'name': 'Groceries', 'description': 'Grocery purchases.', 'type': 'expense'},
        {'name': 'Restaurant', 'description': 'Eating out.', 'type': 'expense'},
        {'name': 'Transportation', 'description': 'Fuel, public transit, etc.', 'type': 'expense'},
        {'name': 'Insurance', 'description': 'Health, car, unemployment, home insurance.', 'type': 'expense'},
        {'name': 'Utilities', 'description': 'Water, electricity, gas.', 'type': 'expense'},
        {'name': 'Entertainment', 'description': 'Movies, games, etc.', 'type': 'expense'},
        {'name': 'Healthcare', 'description': 'Medical, gym, wellness, and fitness expenses.', 'type': 'expense'},
        {'name': 'Education', 'description': 'Tuition, books, etc.', 'type': 'expense'},
        {'name': 'Shopping', 'description': 'Clothes, electronics, etc.', 'type': 'expense'},
        {'name': 'Travel', 'description': 'Flights, hotels, etc.', 'type': 'expense'},
        {'name': 'Gifts', 'description': 'Gifts and donations.', 'type': 'expense'},
        {'name': 'Loans', 'description': 'Repayment of loans.', 'type': 'expense'},
        {'name': 'Pet', 'description': 'Pet insurance, food, healthcare, etc.', 'type': 'expense'},
        {'name': 'Financial Services', 'description': 'Fees from bank, credit card and other financial services., ', 'type': 'expense'},
        {'name': 'Miscellaneous', 'description': 'Other uncategorized expenses.', 'type': 'expense'},

        # Income
        {'name': 'Salary', 'description': 'Wages, salary, etc.', 'type': 'income'},
        {'name': 'Investment', 'description': 'Dividends, interest income.', 'type': 'income'},
        {'name': 'Loans', 'description': 'Money received back from loans.', 'type': 'income'},
        {'name': 'Gifts', 'description': 'Gifts or unexpected income.', 'type': 'income'},
        {'name': 'Miscellaneous', 'description': 'Other uncategorized income.', 'type': 'income'},

        # Transfer
        {'name': 'Investments', 'description': 'Transfer to investments account.', 'type': 'transfer'},
        {'name': 'Savings', 'description': 'Transfer to savings account.', 'type': 'transfer'},
        {'name': 'Savings Withdrawal', 'description': 'Transfer from savings to main account.', 'type': 'transfer'},
        {'name': 'Miscellaneous', 'description': 'Uncategorized transfer.', 'type': 'transfer'},
    ]
    
    for category in default_categories:
        Category.objects.get_or_create(
            name=category['name'],
            type=category['type'],
            defaults={'description': category['description']})    


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
